version: '3'
services:
  mydb:
    image: mysql:5.7
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"

  myweb:
    build: .
    command: /bin/sh #-c "rm -f tmp/pids/server.pid"
    stdin_open: true
    tty: true
    depends_on:
      - mydb
    volumes:
      - .:/furniture-point-server
    ports:
      - "3000:3000"