# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdcb29645822b2d37d57920674bcc034d437735c115586f2016b6173b2d734fd9b1104caf97e4ce42ebe48a8e2ab6844f4ec759968dd95187c7244766b79a09c

test:
  secret_key_base: adc007dd77a6efa70508e8084cbb1d5e5b1907cc42eab7e624e29e3568dbd8f0bb0152e34dd192476fb78eafbd8599ff7aee96d277738201db03c97b9f068e09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
